<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" name="diffbot">
    <!-- VARIABLES -->
    <xacro:property name="base_w" value="0.4"/>
    <xacro:property name="base_d" value="0.3"/>
    <xacro:property name="base_h" value="0.1"/>
    <xacro:property name="wheel_r" value="0.05"/>
    <xacro:property name="wheel_t" value="0.02"/>

    <!-- MACRO:WHEEL  -->
    <xacro:macro name="wheel" params="name x y z">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_t}"/>
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="1.5708 0 0"/>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
        </link>
    </xacro:macro>

    <!-- BASE LINK -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_w} ${base_d} ${base_h}"/>
            </geometry>
            <origin xyz="0 0 ${base_h/2}" />
            <material name="gray">
                <color rgba="0.6 0.6 0.6 1"/>
            </material>
        </visual>
    </link>

    <!-- WHEELS -->
    <xacro:wheel name="left_wheel" x="0" y="0.15" z="0.05"/>
    <xacro:wheel name="right_wheel" x="0" y="-0.15" z="0.05"/>

    <!-- JOINTS -->
    <joint name="left_wheel-joint" type="continuous">
        <parent link= "base_link"/>
        <child link= "left_wheel"/>
        <origin xyz="0 0.15 0.05" />
        <axis xyz="0 1 0"/>
    </joint>
    <joint name="right_wheel_joint" type="continuous">
        <parent link= "base_link"/>
        <child link= "right_wheel"/>
        <origin xyz="0 -0.15 0.05" />
        <axis xyz="0 1 0"/>
    </joint>
</robot>